name: Auto Publish CoalFramework to CocoaPods

on:
  push:
    branches:
      - master

jobs:
  replace_tag_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' 
          bundler-cache: true

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Get Latest Commit Message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "Latest commit message: $COMMIT_MESSAGE"
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"

      - name: Update Tag 0.0.1 with latest commit
        run: |
          git tag -D 0.0.1
          git tag -a 0.0.1 -m "${{ steps.get_commit_message.outputs.commit_message }}"
          git push origin 0.0.1 --force

      - name: Delete Old Pod Version from Trunk
        run: |
          OLD_TAG=${{ steps.get_tag.outputs.latest_tag }}
          pod trunk delete CoalFramework $OLD_TAG || true
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

      - name: Push Podspec to CocoaPods Trunk
        run: |
          NEW_TAG=${{ steps.increment_tag.outputs.new_tag }}
          sed -i '' "s/s.version          = '$OLD_TAG'/s.version          = '$NEW_TAG'/g" CoalFramework.podspec
          pod trunk push CoalFramework.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}